language: php

php:
  - 5.6
  - 7
  - hhvm

before_script:
  - composer self-update
  - composer install

script:
  - composer test

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/logs/clover.xml
